source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'SegueExample'

pod 'R.swift', :git => 'http://github.com/mac-cain13/R.swift'
pod 'SegueManager/R.swift', :path => '../../'
