source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'R.swift', '~> 1.0.0.beta'
pod 'R.swift.Library', '~> 1.0.0.beta'
pod 'SegueManager/R.swift', :path => '../../'
